### ISSUE TITLE
浏览器下载文件进度条一直为0

### ISSUE THREAD

**Issue by tiann** [twoyi/twoyi#2]

**Comment by tiann** [comment]
```
2022-01-08 00:06:21.610 5944-5960/? W/DownloadManager: Path appears to be invalid: /storage/emulated/0/Download/iBiliPlayer-bilih5.apk
2022-01-08 00:06:21.663 5944-6554/? D/DownloadManager: [1] Starting
2022-01-08 00:06:21.692 5944-6554/? W/DownloadManager: [1] Stop requested with status HTTP_DATA_ERROR: Unable to resolve host "dl.hdslb.com": No address associated with hostname
2022-01-08 00:06:21.693 5944-6554/? D/DownloadManager: [1] Finished with status WAITING_TO_RETRY
```

**Comment by tiann** [comment]
```
at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:141)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:90)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at java.net.InetAddress.getAllByNameOnNet(InetAddress.java:1008)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at android.net.Network.getAllByName(Network.java:109)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at android.net.Network$2.lookup(Network.java:230)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:461)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.providers.downloads.DownloadThread.executeDownload(DownloadThread.java:457)
2022-01-08 00:17:31.355 11300-11582/? W/System.err:     at com.android.providers.downloads.DownloadThread.run(DownloadThread.java:307)
2022-01-08 00:17:31.356 11300-11582/? W/System.err: Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
2022-01-08 00:17:31.356 11300-11582/? W/System.err:     at libcore.io.Linux.android_getaddrinfo(Native Method)
2022-01-08 00:17:31.356 11300-11582/? W/System.err:     at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:59)
```

**Comment by tiann** [comment]
fixed in 0.1.10
