### ISSUE TITLE
使用飞书，网络和小程序问题

### ISSUE THREAD

**Issue by PollexLee** [twoyi/twoyi#21]
工作台的banner图片加载不出来；
![Screenshot_2022-01-04-12-42-09-809_io.twoyi.jpg](https://user-images.githubusercontent.com/6780703/148010465-60274ed5-a606-4aea-a05f-fe4e8a4e1b20.jpg)
小程序加载不出来，一直在启动页面；
![Screenshot_2022-01-04-12-41-55-762_io.twoyi.jpg](https://user-images.githubusercontent.com/6780703/148010497-ebcfcf37-3cbf-4e4d-9799-a862e9ebdb83.jpg)

**Comment by PollexLee** [comment]
部分日志：
```kotlin
2022-01-04 14:10:45.884 13175-13175/? W/PackageParser: Failed to parse /data/data/io.twoyi/rootfs
    java.io.FileNotFoundException: AndroidManifest.xml
        at android.content.res.AssetManager.openXmlAssetNative(Native Method)
        at android.content.res.AssetManager.openXmlBlockAsset(AssetManager.java:546)
        at android.content.res.AssetManager.openXmlResourceParser(AssetManager.java:514)
        at android.content.pm.PackageParser.parseApkLite(PackageParser.java:1735)
        at android.content.pm.PackageParser.parseMonolithicPackageLite(PackageParser.java:886)
        at android.content.pm.PackageParser.parseMonolithicPackage(PackageParser.java:1274)
        at android.content.pm.PackageManager.getPackageArchiveInfo(PackageManager.java:4693)
        at com.larksuite.component.dynamicresources.DynamicResourcesManager.b(SourceFile:33816612)
        at com.larksuite.component.dynamicresources.DynamicResourcesManager.a(SourceFile:33882140)
        at com.larksuite.component.dynamicresources.DynamicResourcesManager$1.b(SourceFile:262177)
        at com.larksuite.component.dynamicresources.DynamicResourcesManager$1.a(SourceFile:65536)
        at com.larksuite.component.dynamicresources.DefaultChangeResourcesExecutor.execute(SourceFile:33882175)
        at com.larksuite.component.dynamicresources.DynamicResourcesManager.b(SourceFile:50659364)
        at com.larksuite.component.dynamicresources.DynamicResourcesManager.a(SourceFile:161)
        at com.larksuite.component.dynamicresources.DynamicResourcesFacade.a(SourceFile:33882174)
        at com.ss.android.lark.integrator.core.d.a(SourceFile:17236268)
        at com.ss.android.lark.integrator.core.f.a(SourceFile:196633)
        at com.ss.android.lark.core.impl.CoreApiImpl.initDynamicResources(SourceFile:16973852)
        at com.ss.android.lark.app.task.InitBaseFeatureTask.a(SourceFile:17236088)
        at com.ss.android.lark.app.task.base.AppLauncherTaskScheduler.c(SourceFile:33882154)
        at com.ss.android.lark.app.task.base.AppLauncherTaskScheduler.a(SourceFile:33816631)
        at com.ss.android.lark.app.task.base.AppLauncherTaskScheduler.a(SourceFile:17170470)
        at com.ss.android.lark.app.initiator.b.c(SourceFile:17170565)
        at com.ss.android.lark.app.initiator.i.c(SourceFile:17170452)
        at com.ss.android.lark.app.initiator.a.c(SourceFile:16973849)
        at com.ss.android.lark.app.LarkApplication.onCreate(SourceFile:262194)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1119)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5740)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by PollexLee** [comment]
```kotlin
2022-01-04 14:23:05.390 18909-18936/? E/QTagUidNetworkBytesCollector: Unable to parse file
    java.io.FileNotFoundException: /proc/net/xt_qtaguid/stats: open failed: ENOENT (No such file or directory)
        at libcore.io.IoBridge.open(IoBridge.java:512)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:274)
        at java.io.RandomAccessFile.<init>(RandomAccessFile.java:141)
        at com.facebook.battery.metrics.network.c.c(SourceFile:131078)
        at com.facebook.battery.metrics.network.c.a(SourceFile:17170447)
        at com.facebook.battery.metrics.network.a.a(SourceFile:16973839)
        at com.facebook.battery.metrics.network.b.<init>(SourceFile:16973830)
        at com.ss.android.lark.monitor.traffic.f.a(SourceFile:33882142)
        at com.ss.android.lark.monitor.traffic.TrafficMonitor.a(SourceFile:17301665)
        at com.ss.android.lark.monitor.traffic.TrafficMonitor.<init>(SourceFile:16842755)
        at com.ss.android.lark.monitor.LarkMetrics.a(SourceFile:17236019)
        at com.ss.android.lark.monitor.q.a(SourceFile:17170456)
        at com.ss.android.lark.app.task.InitPerformanceMonitorTask.b(SourceFile:17170548)
        at com.ss.android.lark.app.task.InitPerformanceMonitorTask.a(SourceFile:17104930)
        at com.ss.android.lark.app.taskv2.preload.PreloadTasksFactory$3.a(SourceFile:16973847)
        at com.ss.android.lark.app.taskv2.scheduler.AppLauncherTaskScheduler.b(SourceFile:33882146)
        at com.ss.android.lark.app.taskv2.scheduler.AppLauncherTaskScheduler.a(SourceFile:33751063)
        at com.ss.android.lark.app.taskv2.scheduler.AppLauncherTaskScheduler.d(SourceFile:33751063)
        at com.ss.android.lark.app.taskv2.scheduler.AppLauncherTaskScheduler.lambda$YXp-DBcEquU9k684umcaLEp9h9A(Unknown Source:0)
        at com.ss.android.lark.app.taskv2.scheduler.-$$Lambda$AppLauncherTaskScheduler$YXp-DBcEquU9k684umcaLEp9h9A.run(Unknown Source:6)
        at com.larksuite.framework.thread.g$a.run(SourceFile:393325)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at com.larksuite.framework.thread.m$a.run(SourceFile:262182)
        at java.lang.Thread.run(Thread.java:764)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by PollexLee** [comment]
```kotlin

2022-01-04 14:29:29.559 21732-21732/? W/System.err: java.lang.ClassNotFoundException: com.bytedance.bdturing.verify.IdentityService
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at java.lang.Class.classForName(Native Method)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at java.lang.Class.forName(Class.java:453)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at java.lang.Class.forName(Class.java:378)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.bytedance.bdturing.a.f(SourceFile:327716)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.bytedance.bdturing.a.a(SourceFile:17170491)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.passport.biz_variant.b.a(SourceFile:327796)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.passport.biz_variant.BDTuringServiceImpl.init(SourceFile:196625)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.account_provider.a.b(SourceFile:327753)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.account_provider.b.<init>(SourceFile:17105008)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.integrator.passport.lazy.a.a(SourceFile:262187)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.integrator.passport.PassportApiImpl.getUserId(SourceFile:196629)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.app.task.SpInitorTask$1.getUserId(SourceFile:262173)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.util.share_preference.UserSP.getSpNameSuffix(SourceFile:262169)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.util.share_preference.UserSP.createBaseSharedPreference(SourceFile:196629)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.util.share_preference.UserSP.<init>(SourceFile:131075)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.util.share_preference.UserSP.getInstance(SourceFile:262177)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.featuregating.service.impl.d.g(SourceFile:196629)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.featuregating.service.impl.d.e(SourceFile:327705)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.featuregating.service.impl.d.a(SourceFile:239)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.featuregating.service.impl.d.a(SourceFile:217)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.core.language.a$1$1.a(SourceFile:17104928)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.language.service.impl.a.r(SourceFile:458851)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.language.service.impl.a.p(SourceFile:327697)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.language.service.impl.a.a(SourceFile:623)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.core.impl.CoreApiImpl.updateAppBaseContext(SourceFile:16973852)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.app.taskv2.central.InitLanguageTask.a(SourceFile:17039388)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.app.taskv2.central.InitLanguageTask.a(SourceFile:17104928)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.app.task.base.AppLauncherTaskScheduler.c(SourceFile:33882154)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.app.task.base.AppLauncherTaskScheduler.a(SourceFile:33816631)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.app.task.base.AppLauncherTaskScheduler.a(SourceFile:17170470)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.app.initiator.b.a(SourceFile:17105011)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.app.initiator.i.a(SourceFile:17104916)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.app.initiator.a.a(SourceFile:17039392)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at com.ss.android.lark.app.LarkApplication.attachBaseContext(SourceFile:17170576)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at android.app.Application.attach(Application.java:189)
2022-01-04 14:29:29.559 21732-21732/? W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1103)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5715)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at android.app.ActivityThread.-wrap1(Unknown Source:0)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at android.os.Looper.loop(Looper.java:164)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
2022-01-04 14:29:29.560 21732-21732/? W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by tiann** [comment]
可能与 #38 有关
