### ISSUE TITLE
无法播放视频

### ISSUE THREAD

**Issue by tiann** [twoyi/twoyi#3]

**Comment by tiann** [comment]
```
2022-01-08 00:04:02.416 6062-6457/? E/ACodec: Unable to instantiate a decoder for type 'video/avc' with err 0xfffffffe.
2022-01-08 00:04:02.416 6062-6457/? E/ACodec: signalError(omxError 0xfffffffe, internalError -2)
2022-01-08 00:04:02.416 6062-6455/? E/MediaCodec: Codec reported err 0xfffffffe, actionCode 0, while in state 1
2022-01-08 00:04:02.418 5357-6079/? D/VHWBINDER: process (6062, 6078), binder_thread_read : BR_CLEAR_DEATH_NOTIFICATION_DONE
2022-01-08 00:04:02.419 6062-6453/? W/MediaCodec-JNI: try to release MediaCodec from JMediaCodec::~JMediaCodec()...
2022-01-08 00:04:02.419 6062-6453/? W/MediaCodec-JNI: done releasing MediaCodec from JMediaCodec::~JMediaCodec().
2022-01-08 00:04:02.421 1143-1316/? D/NtpTrustedTime: currentTimeMillis() cache hit
2022-01-08 00:04:02.421 6062-6453/? E/cr_MediaCodecUtil: Failed to create MediaCodec: video/avc, codecType: 0
    java.lang.IllegalArgumentException: Failed to initialize video/avc, error 0xfffffffe
        at android.media.MediaCodec.native_setup(Native Method)
        at android.media.MediaCodec.<init>(MediaCodec.java:1794)
        at android.media.MediaCodec.createDecoderByType(MediaCodec.java:1742)
        at org.chromium.media.MediaCodecUtil.createDecoder(MediaCodecUtil.java:81)
        at org.chromium.media.MediaCodecBridge.create(MediaCodecBridge.java:12)
2022-01-08 00:04:02.421 6127-6449/? E/chromium: [ERROR:render_media_log.cc(30)] MediaEvent: MEDIA_ERROR_LOG_ENTRY {"error":"video decoder initialization failed"}
```

**Comment by tiann** [comment]
不仅是浏览器，抖音等也无法播放

**Comment by tiann** [comment]
mediacodec  的问题，0.6 已修复；还存在其他播放闪退的问题，与 GPU 有关。
