### ISSUE TITLE
来回上拉下拉桌面会导致crash

### ISSUE THREAD

**Issue by wkbin** [twoyi/twoyi#41]

**Comment by tiann** [comment]
0.2.4 版本是否存在此问题？

**Comment by wkbin** [comment]
> 0.2.4 版本是否存在此问题？

已经更新到0.2.5，现在不容易卡住，但是还会有概率卡死，来回上下滑动桌面会掉帧
另外，可否支持高刷？

--Android12 XiamMi12 Pro

**Comment by wkbin** [comment]
`2022-01-15 17:25:17.175 26999-27044/? E/TwoyiSocketServer: start socket failed
    java.io.IOException: accept failed: ENOTSOCK (Socket operation on non-socket)
        at android.net.LocalSocketImpl.accept(LocalSocketImpl.java:306)
        at android.net.LocalServerSocket.accept(LocalServerSocket.java:91)
        at io.twoyi.TwoyiSocketServer.start0(TwoyiSocketServer.java:68)
        at io.twoyi.TwoyiSocketServer.lambda$ipdOdE5YR676s5OHE9vsykGecLQ(Unknown Source:0)
        at io.twoyi.-$$Lambda$TwoyiSocketServer$ipdOdE5YR676s5OHE9vsykGecLQ.run(Unknown Source:2)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:920)
     Caused by: android.system.ErrnoException: accept failed: ENOTSOCK (Socket operation on non-socket)
        at libcore.io.Linux.accept(Native Method)
        at libcore.io.ForwardingOs.accept(ForwardingOs.java:93)
        at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:66)
        at libcore.io.ForwardingOs.accept(ForwardingOs.java:93)
        at android.system.Os.accept(Os.java:57)
        at android.system.Os.accept(Os.java:51)
        at android.net.LocalSocketImpl.accept(LocalSocketImpl.java:303)
        at android.net.LocalServerSocket.accept(LocalServerSocket.java:91) 
        at io.twoyi.TwoyiSocketServer.start0(TwoyiSocketServer.java:68) 
        at io.twoyi.TwoyiSocketServer.lambda$ipdOdE5YR676s5OHE9vsykGecLQ(Unknown Source:0) 
        at io.twoyi.-$$Lambda$TwoyiSocketServer$ipdOdE5YR676s5OHE9vsykGecLQ.run(Unknown Source:2) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:920) 
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG: Cmdline: io.twoyi
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG: pid: 26999, tid: 26999, name: io.twoyi  >>> io.twoyi <<<
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG:       #01 pc 00000000000668dc  /data/app/~~BLfV6QxIq6puAmSrLegSsQ==/io.twoyi-wl4Vc5AgVs5XVaYGZeekqw==/lib/arm64/libtwoyi.so
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG:       #02 pc 00000000000639f0  /data/app/~~BLfV6QxIq6puAmSrLegSsQ==/io.twoyi-wl4Vc5AgVs5XVaYGZeekqw==/lib/arm64/libtwoyi.so
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG:       #03 pc 0000000000063920  /data/app/~~BLfV6QxIq6puAmSrLegSsQ==/io.twoyi-wl4Vc5AgVs5XVaYGZeekqw==/lib/arm64/libtwoyi.so
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG:       #04 pc 0000000000063370  /data/app/~~BLfV6QxIq6puAmSrLegSsQ==/io.twoyi-wl4Vc5AgVs5XVaYGZeekqw==/lib/arm64/libtwoyi.so
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG:       #05 pc 0000000000061de4  /data/app/~~BLfV6QxIq6puAmSrLegSsQ==/io.twoyi-wl4Vc5AgVs5XVaYGZeekqw==/lib/arm64/libtwoyi.so
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG:       #06 pc 00000000000632dc  /data/app/~~BLfV6QxIq6puAmSrLegSsQ==/io.twoyi-wl4Vc5AgVs5XVaYGZeekqw==/lib/arm64/libtwoyi.so
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG:       #07 pc 0000000000063298  /data/app/~~BLfV6QxIq6puAmSrLegSsQ==/io.twoyi-wl4Vc5AgVs5XVaYGZeekqw==/lib/arm64/libtwoyi.so
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG:       #08 pc 000000000002b6bc  /data/app/~~BLfV6QxIq6puAmSrLegSsQ==/io.twoyi-wl4Vc5AgVs5XVaYGZeekqw==/lib/arm64/libtwoyi.so
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG:       #09 pc 000000000002e1bc  /data/app/~~BLfV6QxIq6puAmSrLegSsQ==/io.twoyi-wl4Vc5AgVs5XVaYGZeekqw==/lib/arm64/libtwoyi.so (handle_touch+92)
2022-01-15 17:25:17.842 28114-28114/? A/DEBUG:       #12 pc 00000000002f7fec  /data/app/~~BLfV6QxIq6puAmSrLegSsQ==/io.twoyi-wl4Vc5AgVs5XVaYGZeekqw==/oat/arm64/base.vdex`

**Comment by tiann** [comment]
0.3.5 版本是否还会卡死？

**Comment by tiann** [comment]
fixed in https://github.com/twoyi/twoyi/commit/f5ed035bc3b0458ee2f954e703246923f1ccb491
