### ISSUE TITLE
[bug] 0.3.5 Has no libtwoyi.so  

### ISSUE THREAD

**Issue by hhhaiai** [twoyi/twoyi#46]
## Error source

* File: Render2Activity.java
* code
    ``` java
        static {
            System.loadLibrary("twoyi");
        }
    ```

## EXCEPTION

```
2022-02-09 11:14:14.790 1995-1995/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.twoyi, PID: 1995
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libtwoyi.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at io.twoyi.Render2Activity.<clinit>(Render2Activity.java:58)
        at java.lang.Class.newInstance(Native Method)
        at android.app.AppComponentFactory.instantiateActivity(AppComponentFactory.java:95)
        at androidx.core.app.CoreComponentFactory.instantiateActivity(CoreComponentFactory.java:45)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1253)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3335)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3595)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:85)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2066)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7664)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

**Comment by hhhaiai** [comment]
upload libtwoyi.so into this UI platform

**Comment by hhhaiai** [comment]
@tiann

**Comment by tiann** [comment]
please run this script to build libtwoyi.so: https://github.com/twoyi/twoyi/blob/main/app/rs/build_rs.sh

**Comment by hhhaiai** [comment]
ok, thx
