### ISSUE TITLE
[自己编译] 运行异常

### ISSUE THREAD

**Issue by hhhaiai** [twoyi/twoyi#54]
## all log
```
2022-02-10 11:55:17.237 30533-30533/? W/init: type=1400 audit(0.0:39617): avc: granted { execute } for name="surfaceflinger" dev="dm-5" ino=40081 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:app_data_file:s0:c512,c768 tclass=file app=io.twoyi
2022-02-10 11:55:17.267 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::maxFrameBufferAcquiredBuffers retrieved: 3
2022-02-10 11:55:17.269 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::startGraphicsAllocatorService retrieved: 0
2022-02-10 11:55:17.270 30533-30533/? I/SurfaceFlinger: SurfaceFlinger is starting
2022-02-10 11:55:17.270 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::vsyncEventPhaseOffsetNs retrieved: 1000000 (default)
2022-02-10 11:55:17.270 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::vsyncSfEventPhaseOffsetNs retrieved: 1000000 (default)
2022-02-10 11:55:17.271 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::maxVirtualDisplaySize retrieved: 0 (default)
2022-02-10 11:55:17.271 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasSyncFramework retrieved: 1
2022-02-10 11:55:17.271 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::useContextPriority retrieved: 0 (default)
2022-02-10 11:55:17.271 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::presentTimeOffsetFromVSyncNs retrieved: 0
2022-02-10 11:55:17.271 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::useHwcForRGBtoYUV retrieved: 0
2022-02-10 11:55:17.271 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::maxFrameBufferAcquiredBuffers retrieved: 3
2022-02-10 11:55:17.271 30533-30533/? E/DispSync: Couldn't set SCHED_FIFO for DispSyncThread
2022-02-10 11:55:17.271 30533-30533/? I/SurfaceFlinger: Enabling HWC virtual displays
2022-02-10 11:55:17.271 30533-30533/? I/SurfaceFlinger: Disabling Triple Buffering
2022-02-10 11:55:17.271 30533-30533/? I/SurfaceFlinger: SurfaceFlinger's main thread ready to run. Initializing graphics H/W...
2022-02-10 11:55:17.272 30533-30533/? E/libEGL: load_driver(/vendor/lib64/egl/libGLES_emulation.so): dlopen failed: library "/vendor/lib64/egl/libGLES_emulation.so" not found
2022-02-10 11:55:17.290 30229-30543/io.twoyi I/CLIENT_EGL: rcGetEGLVersion: 1 5
2022-02-10 11:55:17.292 30533-30533/? I//system/bin/surfaceflinger: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
```

## 错误?

```
load_driver(/vendor/lib64/egl/libGLES_emulation.so): dlopen failed: library "/vendor/lib64/egl/libGLES_emulation.so" not found
```

**Comment by tiann** [comment]
这个不影响运行，可以忽略。

**Comment by hhhaiai** [comment]
你0.35的release的 rootfs.7z 可以打开app。 但是进入后两仪设置打不开，整体卡顿。


能不能分享个可用的rootfs.7z

**Comment by hhhaiai** [comment]
>启动有部分异常

## log 1
```
2022-02-10 12:04:46.555 4697-4697/? W/StatusBar: isKeyguardSecure() called before startKeyguard(), returning false
    java.lang.Throwable
        at com.android.systemui.statusbar.phone.StatusBar.isKeyguardSecure(StatusBar.java:7607)
        at com.android.systemui.statusbar.phone.StatusBar.isCameraAllowedByAdmin(StatusBar.java:5484)
        at com.android.systemui.statusbar.phone.KeyguardBottomAreaView$DefaultRightButton.getIcon(KeyguardBottomAreaView.java:856)
        at com.android.systemui.statusbar.phone.KeyguardBottomAreaView.updateCameraVisibility(KeyguardBottomAreaView.java:382)
        at com.android.systemui.statusbar.phone.KeyguardBottomAreaView.setStatusBar(KeyguardBottomAreaView.java:351)
        at com.android.systemui.statusbar.phone.NotificationPanelView.setStatusBar(NotificationPanelView.java:252)
        at com.android.systemui.statusbar.phone.StatusBar.makeStatusBarView(StatusBar.java:1025)
        at com.android.systemui.statusbar.phone.StatusBar.addStatusBarWindow(StatusBar.java:3712)
        at com.android.systemui.statusbar.phone.StatusBar.createAndAddWindows(StatusBar.java:3708)
        at com.android.systemui.statusbar.phone.StatusBar.start(StatusBar.java:895)
        at com.android.systemui.SystemBars.createStatusBarFromConfig(SystemBars.java:71)
        at com.android.systemui.SystemBars.start(SystemBars.java:42)
        at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:215)
        at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:164)
        at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:33)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2022-02-10 12:04:46.581 4697-4697/? I/StatusBar: isKeyguardShowing() called before startKeyguard(), returning true
2022-02-10 12:04:46.581 4697-4697/? W/StatusBar: isKeyguardSecure() called before startKeyguard(), returning false
    java.lang.Throwable
        at com.android.systemui.statusbar.phone.StatusBar.isKeyguardSecure(StatusBar.java:7607)
        at com.android.systemui.statusbar.phone.StatusBar.isCameraAllowedByAdmin(StatusBar.java:5484)
        at com.android.systemui.statusbar.phone.KeyguardBottomAreaView$DefaultRightButton.getIcon(KeyguardBottomAreaView.java:856)
        at com.android.systemui.statusbar.phone.KeyguardBottomAreaView.updateCameraVisibility(KeyguardBottomAreaView.java:382)
        at com.android.systemui.statusbar.phone.KeyguardBottomAreaView.setUserSetupComplete(KeyguardBottomAreaView.java:360)
        at com.android.systemui.statusbar.phone.NotificationPanelView.setUserSetupComplete(NotificationPanelView.java:2655)
        at com.android.systemui.statusbar.phone.StatusBar.makeStatusBarView(StatusBar.java:1168)
        at com.android.systemui.statusbar.phone.StatusBar.addStatusBarWindow(StatusBar.java:3712)
        at com.android.systemui.statusbar.phone.StatusBar.createAndAddWindows(StatusBar.java:3708)
        at com.android.systemui.statusbar.phone.StatusBar.start(StatusBar.java:895)
        at com.android.systemui.SystemBars.createStatusBarFromConfig(SystemBars.java:71)
        at com.android.systemui.SystemBars.start(SystemBars.java:42)
        at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:215)
        at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:164)
        at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:33)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2022-02-10 12:04:46.587 4697-4893/? W/Tile.BluetoothTile: Error in handleSetListening
    java.lang.NullPointerException: Attempt to invoke interface method 'void com.android.systemui.statusbar.policy.BluetoothController.addCallback(java.lang.Object)' on a null object reference
        at com.android.systemui.qs.tiles.BluetoothTile.handleSetListening(BluetoothTile.java:80)
        at com.android.systemui.qs.tileimpl.QSTileImpl$H.handleMessage(QSTileImpl.java:461)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2022-02-10 12:04:46.587 4697-4893/? W/Tile.BluetoothTile: Error in handleRefreshState
    java.lang.NullPointerException: Attempt to invoke interface method 'boolean com.android.systemui.statusbar.policy.BluetoothController.isBluetoothEnabled()' on a null object reference
        at com.android.systemui.qs.tiles.BluetoothTile.handleUpdateState(BluetoothTile.java:118)
        at com.android.systemui.qs.tiles.BluetoothTile.handleUpdateState(BluetoothTile.java:116)
        at com.android.systemui.qs.tileimpl.QSTileImpl.handleRefreshState(QSTileImpl.java:287)
        at com.android.systemui.qs.tileimpl.QSTileImpl$H.handleMessage(QSTileImpl.java:440)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
2022-02-10 12:04:46.587 4697-4697/? E/BluetoothAdapter: Bluetooth binder is null
2022-02-10 12:04:46.594 4697-4893/? I/CameraManagerGlobal: Connecting to camera service
2022-02-10 12:04:46.596 4961-5008/? W/MediaProfiles: Could not find a validated xml file. Using the default instance instead.
2022-02-10 12:04:46.605 4697-4697/? I/StatusBar: isKeyguardShowing() called before startKeyguard(), returning true
2022-02-10 12:04:46.605 4697-4697/? W/StatusBar: isKeyguardSecure() called before startKeyguard(), returning false
    java.lang.Throwable
        at com.android.systemui.statusbar.phone.StatusBar.isKeyguardSecure(StatusBar.java:7607)
        at com.android.systemui.statusbar.phone.StatusBar.isCameraAllowedByAdmin(StatusBar.java:5484)
        at com.android.systemui.statusbar.phone.KeyguardBottomAreaView$DefaultRightButton.getIcon(KeyguardBottomAreaView.java:856)
        at com.android.systemui.statusbar.phone.KeyguardBottomAreaView.updateCameraVisibility(KeyguardBottomAreaView.java:382)
        at com.android.systemui.statusbar.phone.KeyguardBottomAreaView.setUserSetupComplete(KeyguardBottomAreaView.java:360)
        at com.android.systemui.statusbar.phone.NotificationPanelView.setUserSetupComplete(NotificationPanelView.java:2655)
        at com.android.systemui.statusbar.phone.StatusBar$1.onUserSetupChanged(StatusBar.java:527)
        at com.android.systemui.statusbar.policy.DeviceProvisionedControllerImpl.addCallback(DeviceProvisionedControllerImpl.java:69)
        at com.android.systemui.statusbar.policy.DeviceProvisionedControllerImpl.addCallback(DeviceProvisionedControllerImpl.java:63)
        at com.android.systemui.statusbar.phone.StatusBar.makeStatusBarView(StatusBar.java:1258)
        at com.android.systemui.statusbar.phone.StatusBar.addStatusBarWindow(StatusBar.java:3712)
        at com.android.systemui.statusbar.phone.StatusBar.createAndAddWindows(StatusBar.java:3708)
        at com.android.systemui.statusbar.phone.StatusBar.start(StatusBar.java:895)
        at com.android.systemui.SystemBars.createStatusBarFromConfig(SystemBars.java:71)
        at com.android.systemui.SystemBars.start(SystemBars.java:42)
        at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:215)
        at com.android.systemui.SystemUIApplication.startServicesIfNeeded(SystemUIApplication.java:164)
        at com.android.systemui.SystemUIService.onCreate(SystemUIService.java:33)
        at android.app.ActivityThread.handleCreateService(ActivityThread.java:3339)
        at android.app.ActivityThread.-wrap4(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1677)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
2022-02-10 12:04:46.623 4697-4697/? W/TelecomManager: Telecom Service not found.
2022-02-10 12:04:46.681 4301-4838/io.twoyi I/CLIENT_EGL: createColorBuffer: 23
2022-02-10 12:04:46.683 4301-4838/io.twoyi I/CLIENT_EGL: createColorBuffer: 24
2022-02-10 12:04:46.683 4301-4838/io.twoyi I/CLIENT_EGL: createColorBuffer: 25
2022-02-10 12:04:46.684 4301-5021/io.twoyi I/CLIENT_EGL: rcGetEGLVersion: 1 5
2022-02-10 12:04:46.689 4697-4919/? I/zygote64: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2022-02-10 12:04:46.689 4697-4919/? I/OpenGLRenderer: Initialized EGL, version 1.4
2022-02-10 12:04:46.690 4697-4919/? W/EGL_emulation: eglCreateContext version: 2
2022-02-10 12:04:46.691 4301-5021/io.twoyi I/CLIENT_EGL: createWindowSurface: 1x1
2022-02-10 12:04:46.691 4301-5021/io.twoyi I/CLIENT_EGL: createColorBuffer: 28
2022-02-10 12:04:46.691 4301-5021/io.twoyi I/CLIENT_EGL: rcGetGLString: GL_OES_EGL_image GL_OES_EGL_image_external GL_OES_vertex_half_float GL_OES_rgb8_rgba8 GL_OES_compressed_ETC1_RGB8_texture GL_OES_texture_npot GL_OES_depth24 GL_OES_packed_depth_stencil GL_OES_depth_texture GL_OES_texture_float GL_OES_texture_float_linear GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_element_index_uint GL_OES_standard_derivatives
2022-02-10 12:04:46.691 4301-5021/io.twoyi I/CLIENT_EGL: rcGetGLString: OpenGL ES 2.0
2022-02-10 12:04:46.692 4374-4812/? E/SurfaceFlinger: ro.sf.lcd_density must be defined as a build property
2022-02-10 12:04:46.704 4301-5021/io.twoyi I/CLIENT_EGL: createWindowSurface: 1440x161
2022-02-10 12:04:46.745 4301-4896/io.twoyi I/CLIENT_EGL: createColorBuffer: 30
2022-02-10 12:04:46.746 4301-4896/io.twoyi I/CLIENT_EGL: createColorBuffer: 31
2022-02-10 12:04:46.746 4301-4896/io.twoyi I/CLIENT_EGL: createColorBuffer: 32
2022-02-10 12:04:46.747 4301-5021/io.twoyi I/CLIENT_EGL: createWindowSurface: 1440x81
```

## log2

```
2022-02-10 12:04:46.931 4520-4520/? W/system_server: type=1400 audit(0.0:68187): avc: granted { open } for path="/dev/ashmem" dev="tmpfs" ino=28384 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:ashmem_device:s0 tclass=chr_file app=io.twoyi
2022-02-10 12:04:46.938 4520-5032/? E/BootReceiver: Can't log boot events
    java.io.FileNotFoundException: /proc/version (Permission denied)
        at java.io.FileInputStream.open0(Native Method)
        at java.io.FileInputStream.open(FileInputStream.java:200)
        at java.io.FileInputStream.<init>(FileInputStream.java:150)
        at android.os.FileUtils.readTextFile(FileUtils.java:262)
        at com.android.server.BootReceiver.getCurrentBootHeaders(BootReceiver.java:164)
        at com.android.server.BootReceiver.getBootHeadersToLogAndUpdate(BootReceiver.java:171)
        at com.android.server.BootReceiver.logBootEvents(BootReceiver.java:190)
        at com.android.server.BootReceiver.-wrap2(Unknown Source:0)
        at com.android.server.BootReceiver$1.run(BootReceiver.java:121)
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Socket name not whitelisted : /data/data/io.twoyi/rootfs/dev/socket/zygote (fd=3)
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Unable to stat fd 5: Permission denied
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Socket name not whitelisted : /data/data/io.twoyi/rootfs/dev/socket/zygote (fd=7)
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Not whitelisted : /data/data/io.twoyi/log.txt
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Not whitelisted : /data/data/io.twoyi/log.txt
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Unsupported AF_UNIX socket (fd=54) with abstract address.
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Unsupported AF_UNIX socket (fd=60) with empty path.
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Unsupported AF_UNIX socket (fd=61) with empty path.
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Unsupported AF_UNIX socket (fd=63) with empty path.
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Unsupported AF_UNIX socket (fd=64) with empty path.
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Socket name not whitelisted : /data/data/io.twoyi/rootfs/dev/input/key0 (fd=67)
2022-02-10 12:04:46.940 4343-4343/? E/zygote64: Socket name not whitelisted : /data/data/io.twoyi/rootfs/dev/input/touch (fd=68)
2022-02-10 12:04:46.944 4697-4702/? I/zygote64: Do partial code cache collection, code=29KB, data=24KB
2022-02-10 12:04:46.944 4697-4702/? I/zygote64: After code cache collection, code=29KB, data=24KB
2022-02-10 12:04:46.944 4697-4702/? I/zygote64: Increasing code cache capacity to 128KB
2022-02-10 12:04:46.948 4520-4520/? I/ActivityManager: Start proc 5034:com.android.inputmethod.latin/u0a25 for broadcast com.android.inputmethod.latin/.SystemBroadcastReceiver
2022-02-10 12:04:46.949 4520-4539/? W/UsageStatsService: Failed to update counter set: java.io.FileNotFoundException: /proc/uid_procstat/set (Permission denied)
2022-02-10 12:04:46.973 5034-5034/? I/zygote64: The ClassLoaderContext is a special shared library.
2022-02-10 12:04:46.980 5034-5034/? I/SystemBroadcastReceiver: Boot has been completed
2022-02-10 12:04:46.980 5034-5034/? I/SystemBroadcastReceiver: toggleAppIcon() : FLAG_SYSTEM = true
2022-02-10 12:04:46.987 5034-5034/? I/SystemBroadcastReceiver: Killing my process: pid=5034
2022-02-10 12:04:46.987 5034-5034/? I/Process: Sending signal. PID: 5034 SIG: 9
2022-02-10 12:04:46.995 4520-4847/? I/ActivityManager: Process com.android.inputmethod.latin (pid 5034) has died: fore RCVR
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Socket name not whitelisted : /data/data/io.twoyi/rootfs/dev/socket/zygote (fd=3)
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Unable to stat fd 5: Permission denied
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Socket name not whitelisted : /data/data/io.twoyi/rootfs/dev/socket/zygote (fd=7)
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Not whitelisted : /data/data/io.twoyi/log.txt
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Not whitelisted : /data/data/io.twoyi/log.txt
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Unsupported AF_UNIX socket (fd=54) with abstract address.
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Unsupported AF_UNIX socket (fd=60) with empty path.
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Unsupported AF_UNIX socket (fd=61) with empty path.
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Unsupported AF_UNIX socket (fd=63) with empty path.
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Unsupported AF_UNIX socket (fd=64) with empty path.
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Socket name not whitelisted : /data/data/io.twoyi/rootfs/dev/input/key0 (fd=67)
2022-02-10 12:04:47.002 4343-4343/? E/zygote64: Socket name not whitelisted : /data/data/io.twoyi/rootfs/dev/input/touch (fd=68)
```

**Comment by hhhaiai** [comment]
## 打开app，然后黑屏

```
2022-02-10 12:07:45.114 4374-4552/? E/BufferQueueProducer: [Splash Screen com.android.launcher3#0] queueBuffer: BufferQueue has been abandoned
2022-02-10 12:07:45.114 4520-4585/? E/Surface: queueBuffer: error queuing buffer to SurfaceTexture, -19
2022-02-10 12:07:45.114 4520-4585/? E/Surface: queueBuffer (handle=0x7b18285b50) failed (No such device)
2022-02-10 12:07:45.115 4520-4585/? E/ViewRootImpl[launcher3]: Could not unlock surface
    java.lang.IllegalArgumentException
        at android.view.Surface.nativeUnlockCanvasAndPost(Native Method)
        at android.view.Surface.unlockSwCanvasAndPost(Surface.java:355)
        at android.view.Surface.unlockCanvasAndPost(Surface.java:336)
        at android.view.ViewRootImpl.drawSoftware(ViewRootImpl.java:3116)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3019)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2806)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2359)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1392)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:658)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.os.HandlerThread.run(HandlerThread.java:65)
        at com.android.server.ServiceThread.run(ServiceThread.java:46)

```

**Comment by hhhaiai** [comment]
> 这个不影响运行，可以忽略。

ok，thx.

**Comment by tiann** [comment]
你上面列的那些错误都不影响运行的

**Comment by Ahackerl** [comment]
能不能出个文档大概说下aosp怎么修改

**Comment by hhhaiai** [comment]
> 你上面列的那些错误都不影响运行的

现在可以打开两仪，0.3.5的root.fs可以运行，但是不能导入app，能分享个可以玩的rootfs.7z么

**Comment by hhhaiai** [comment]
> 能不能出个文档大概说下aosp怎么修改

理论上修改和谷歌rom类似，提供了个依赖的模快的项目 [platform_manifest](https://github.com/twoyi/platform_manifest)

repo下载调试呗
