### ISSUE TITLE
点击开发者选项无响应

### ISSUE THREAD

**Issue by tiann** [twoyi/twoyi#6]
```txt
2022-01-03 13:47:44.208 29983-29983/? E/SystemServiceRegistry: No service published for: oem_lock
    android.os.ServiceManager$ServiceNotFoundException: No service published for: oem_lock
        at android.os.ServiceManager.getServiceOrThrow(ServiceManager.java:75)
        at android.app.SystemServiceRegistry$72.createService(SystemServiceRegistry.java:787)
        at android.app.SystemServiceRegistry$72.createService(SystemServiceRegistry.java:785)
        at android.app.SystemServiceRegistry$StaticServiceFetcher.getService(SystemServiceRegistry.java:987)
        at android.app.SystemServiceRegistry.getSystemService(SystemServiceRegistry.java:914)
        at android.app.ContextImpl.getSystemService(ContextImpl.java:1667)
        at android.view.ContextThemeWrapper.getSystemService(ContextThemeWrapper.java:171)
        at android.app.Activity.getSystemService(Activity.java:5925)
        at com.android.settings.development.DevelopmentSettings.showEnableOemUnlockPreference(DevelopmentSettings.java:1061)
        at com.android.settings.development.DevelopmentSettings.onCreate(DevelopmentSettings.java:451)
        at android.app.Fragment.performCreate(Fragment.java:2489)
        at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1237)
        at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2407)
        at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2186)
        at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2142)
        at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2043)
        at android.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:799)
        at com.android.settings.SettingsActivity.switchToFragment(SettingsActivity.java:748)
        at com.android.settings.SettingsActivity.launchSettingFragment(SettingsActivity.java:435)
        at com.android.settings.SettingsActivity.onCreate(SettingsActivity.java:327)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807
```

**Comment by tiann** [comment]
上面那个错误不影响，真正的错误应该是这个：

```
/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x28 in tid 30821 (vold), pid 30819 (vold)
```

**Comment by tiann** [comment]
0.1.7 修复。
