### ISSUE TITLE
编译后运行闪退

### ISSUE THREAD

**Issue by crazyn2** [twoyi/twoyi#61]
操作系统：Ubuntu20.04 LTS
Android Studio: 2021.1.1版本
java环境: openjdk-11
ndk:22.1.7171670/21.4.7075529/21.0.6113669(这些版本都试过了)
按照步骤配置了rust, ndk，把roofts.7z放到assets/, 编译好的两仪运行出现启动系统动画，大概3秒后直接闪退，日志没有报错

![Screenshot from 2022-02-11 19-29-40](https://user-images.githubusercontent.com/45783572/153584211-eef3ba09-5fd2-45a2-877a-206e664d942a.png)
以下是日志:
2022-02-11 19:28:59.743 20130-20130/? I/io.twoyi: Late-enabling -Xcheck:jni
2022-02-11 19:28:59.966 20130-20130/io.twoyi I/io.twoyi: The ClassLoaderContext is a special shared library.
2022-02-11 19:28:59.983 20130-20130/io.twoyi I/Perf: Connecting to perf service.
2022-02-11 19:29:00.047 20130-20161/io.twoyi I/io.twoyi: The ClassLoaderContext is a special shared library.
2022-02-11 19:29:00.038 20130-20130/io.twoyi W/Binder:intercep: type=1400 audit(0.0:2667012): avc: denied { getattr } for path="/data/data/com.miui.contentcatcher" dev="dm-1" ino=3145907 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:system_app_data_file:s0 tclass=dir permissive=0
2022-02-11 19:29:00.055 20130-20162/io.twoyi W/System.err: java.io.FileNotFoundException: rootfs.7z
2022-02-11 19:29:00.056 20130-20162/io.twoyi W/System.err:     at android.content.res.AssetManager.nativeOpenAsset(Native Method)
2022-02-11 19:29:00.056 20130-20162/io.twoyi W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:748)
2022-02-11 19:29:00.056 20130-20162/io.twoyi W/System.err:     at android.content.res.AssetManager.open(AssetManager.java:725)
2022-02-11 19:29:00.057 20130-20162/io.twoyi W/System.err:     at io.twoyi.utils.RomUtil.extractRootfs(RomUtil.java:45)
2022-02-11 19:29:00.057 20130-20162/io.twoyi W/System.err:     at io.twoyi.Render2Activity.lambda$onCreate$1$io-twoyi-Render2Activity(Render2Activity.java:127)
2022-02-11 19:29:00.057 20130-20162/io.twoyi W/System.err:     at io.twoyi.Render2Activity$$ExternalSyntheticLambda3.run(Unknown Source:2)
2022-02-11 19:29:00.057 20130-20162/io.twoyi W/System.err:     at java.lang.Thread.run(Thread.java:764)
2022-02-11 19:29:00.060 20130-20161/io.twoyi D/ViewContentFactory: initViewContentFetcherClass
2022-02-11 19:29:00.060 20130-20161/io.twoyi D/ViewContentFactory: getInterceptorPackageInfo
2022-02-11 19:29:00.060 20130-20161/io.twoyi W/io.twoyi: Accessing hidden method Landroid/app/AppGlobals;->getInitialApplication()Landroid/app/Application; (light greylist, linking)
2022-02-11 19:29:00.062 20130-20161/io.twoyi D/ViewContentFactory: getInitialApplication took 2ms
2022-02-11 19:29:00.062 20130-20161/io.twoyi D/ViewContentFactory: packageInfo.packageName: com.miui.catcherpatch
2022-02-11 19:29:00.065 20130-20162/io.twoyi I/System.out: extract rootfs, read assets: 4 un7z: 8
2022-02-11 19:29:00.068 20130-20130/io.twoyi W/Binder:intercep: type=1400 audit(0.0:2667013): avc: denied { getattr } for path="/data/data/com.miui.catcherpatch" dev="dm-1" ino=3146195 scontext=u:r:untrusted_app_27:s0:c512,c768 tcontext=u:object_r:system_app_data_file:s0 tclass=dir permissive=0
2022-02-11 19:29:00.076 20130-20161/io.twoyi D/ViewContentFactory: initViewContentFetcherClass took 17ms
2022-02-11 19:29:00.077 20130-20161/io.twoyi I/ContentCatcher: ViewContentFetcher : ViewContentFetcher
2022-02-11 19:29:00.077 20130-20161/io.twoyi D/ViewContentFactory: createInterceptor took 17ms
2022-02-11 19:29:00.105 20130-20164/io.twoyi I/Adreno: QUALCOMM build                   : ce8a911, I385ac5a262
    Build Date                       : 03/28/19
    OpenGL ES Shader Compiler Version: EV031.25.03.01
    Local Branch                     : 
    Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.7.2.R1.09.00.00.442.052
    Remote Branch                    : NONE
    Reconstruct Branch               : NOTHING
2022-02-11 19:29:00.105 20130-20164/io.twoyi I/Adreno: Build Config                     : S L 6.0.7 AArch64
2022-02-11 19:29:00.105 20130-20164/io.twoyi D/vndksupport: Loading /vendor/lib64/hw/gralloc.sdm660.so from current namespace instead of sphal namespace.
2022-02-11 19:29:00.110 20130-20164/io.twoyi I/Adreno: PFP: 0x005ff112, ME: 0x005ff066
2022-02-11 19:29:00.113 20130-20164/io.twoyi I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasWideColorDisplay retrieved: 0
2022-02-11 19:29:00.113 20130-20164/io.twoyi I/ConfigStore: android::hardware::configstore::V1_0::ISurfaceFlingerConfigs::hasHDRDisplay retrieved: 0
2022-02-11 19:29:00.114 20130-20164/io.twoyi I/OpenGLRenderer: Initialized EGL, version 1.4
2022-02-11 19:29:00.114 20130-20164/io.twoyi D/OpenGLRenderer: Swap behavior 2
2022-02-11 19:29:00.133 20130-20130/io.twoyi W/Render2Activity: current fps: 60.0
2022-02-11 19:29:00.133 20130-20130/io.twoyi I/CLIENT_EGL: twoyi: renderer_init width: 1080, height: 1920, fps: 60
2022-02-11 19:29:00.134 20130-20168/io.twoyi I/CLIENT_EGL: twoyi: win: 0x0000007557780010
2022-02-11 19:29:00.140 20130-20168/io.twoyi D/libOpenglRender: startOpenGLRenderer, width: 1080, height: 1920, win: 0x7557780010, xdpi: 403, ydpi: 403
2022-02-11 19:29:00.145 20130-20168/io.twoyi D/libOpenglRender: initLibrary: 1
2022-02-11 19:29:00.145 20130-20168/io.twoyi I/CLIENT_EGL: RenderWindow: CMD_INITIALIZE w=1080 h=1920
2022-02-11 19:29:00.145 20130-20168/io.twoyi I/CLIENT_EGL: FrameBuffer::initialize
2022-02-11 19:29:00.145 20130-20168/io.twoyi I/CLIENT_EGL: call eglInitialize
2022-02-11 19:29:00.145 20130-20168/io.twoyi I/CLIENT_EGL: egl: 1 4
2022-02-11 19:29:00.149 20130-20168/io.twoyi I/CLIENT_EGL: attempting to create egl context
2022-02-11 19:29:00.150 20130-20168/io.twoyi I/CLIENT_EGL: attempting to create egl pbuffer context
2022-02-11 19:29:00.151 20130-20168/io.twoyi I/CLIENT_EGL: context creation successful
2022-02-11 19:29:00.151 20130-20168/io.twoyi I/CLIENT_EGL: m_pbufSurface: 0x754bcbd780, m_pbufContext: 0x754bcbd680
2022-02-11 19:29:00.151 20130-20168/io.twoyi I/CLIENT_EGL: attempting to make context current
2022-02-11 19:29:00.152 20130-20168/io.twoyi I/CLIENT_EGL: context-current successful
2022-02-11 19:29:00.152 20130-20168/io.twoyi I/CLIENT_EGL: host system has enough extensions
2022-02-11 19:29:00.152 20130-20168/io.twoyi I/CLIENT_EGL: There are sufficient EGLconfigs available
2022-02-11 19:29:00.153 20130-20130/io.twoyi I/Render2Activity: surfaceCreated
2022-02-11 19:29:00.154 20130-20130/io.twoyi W/libOpenglRender: resetSubWindow but fb is null!
2022-02-11 19:29:00.154 20130-20130/io.twoyi I/Render2Activity: surfaceChanged: 1080x1920
2022-02-11 19:29:00.161 20130-20168/io.twoyi I/CLIENT_EGL: libui.so handle: 0x754bcef4e0
2022-02-11 19:29:00.161 20130-20168/io.twoyi I/CLIENT_EGL: sym1: 0x75ebedd3b4, sym2: 0x75ebede4b8
2022-02-11 19:29:00.161 20130-20168/io.twoyi I/CLIENT_EGL: GraphicBuffer_unflatten: 0x75ebede4b8, GraphicBuffer_create: 0x75ebedd3b4
2022-02-11 19:29:00.161 20130-20168/io.twoyi I/CLIENT_EGL: basic EGL initialization successful
2022-02-11 19:29:00.162 20130-20168/io.twoyi I/CLIENT_EGL: OpenGL renderer initialized successfully
2022-02-11 19:29:00.162 20130-20168/io.twoyi D/libOpenglRender: initOpenGLRenderer: 1
2022-02-11 19:29:00.162 20130-20168/io.twoyi I/CLIENT_EGL: setupSubWindow called, m_subWin: 0x0, m_appWin: 0x7557780010
2022-02-11 19:29:00.163 20130-20164/io.twoyi D/vndksupport: Loading /vendor/lib64/hw/android.hardware.graphics.mapper@2.0-impl.so from current namespace instead of sphal namespace.
2022-02-11 19:29:00.163 20130-20168/io.twoyi I/CLIENT_EGL: m_lastPostedColorBuffer: 0
2022-02-11 19:29:00.163 20130-20168/io.twoyi I/CLIENT_EGL: first draw, display: 0x1, surface: 0x754bceef00
2022-02-11 19:29:00.166 20130-20164/io.twoyi D/vndksupport: Loading /vendor/lib64/hw/gralloc.sdm660.so from current namespace instead of sphal namespace.
2022-02-11 19:29:02.296 20130-20130/io.twoyi W/io.twoyi: Accessing hidden field Landroid/view/MotionEvent;->mNativePtr:J (light greylist, JNI)
2022-02-11 19:29:07.992 20130-20158/io.twoyi I/io.twoyi: ProcessProfilingInfo new_methods=0 is saved saved_to_disk=0 resolve_classes_delay=8000
2022-02-11 19:29:15.144 20130-20165/io.twoyi I/io.twoyi: System.exit called, status: 0
2022-02-11 19:29:15.144 20130-20165/io.twoyi I/AndroidRuntime: VM exiting with result code 0, cleanup skipped.

**Comment by crazyn2** [comment]
问题已经解决，rootfs.7z 应该放在app/src/main/assets，而不是app/assets
