### ISSUE TITLE
知乎无法正常使用,点击文章后,知乎黑屏无响应,下拉通知栏,导航栏出现,能正常回到桌面进行其他操作（证明两仪没有死）

### ISSUE THREAD

**Issue by EscapeA** [twoyi/twoyi#68]
**日志链接**
https://wwi.lanzouo.com/iLcVD005wo7e

**部分日志如下**:
Process: com.zhihu.android
PID: 27685
Flags: 0x38d83e44
Package: com.zhihu.android v8730 (8.7.0)
Foreground: Yes
Subject: Sentry
Build: Android/twoyi_arm64/twoyi_arm64:8.1.0/OC/root01131710:user/test-keys

android.util.Log$TerribleFailure: Fatal error during SentryAndroid.init(...)
	at android.util.Log.wtf(Log.java:299)
	at android.util.Log.wtf(Log.java:294)
	at io.sentry.android.core.AndroidLogger.log(AndroidLogger.java:49)
	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:93)
	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:52)
	at com.zhihu.android.app.report.SentryCrashLogger.init(SentryCrashLogger.kt:86)
	at com.zhihu.android.app.report.o.c(LazyCrashInitializer.java:103)
	at com.zhihu.android.app.report.o.b(LazyCrashInitializer.java:94)
	at com.zhihu.android.app.report.o.a(LazyCrashInitializer.java:23)
	at com.zhihu.android.app.report.o$2.execute(LazyCrashInitializer.java:179)
	at com.zhihu.android.x.c.run(NamedRunnable.kt:24)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
	at com.zhihu.android.x.a.c.run(RulerThread.java:101)
Caused by: java.lang.reflect.InvocationTargetException
	at java.lang.reflect.Constructor.newInstance0(Native Method)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
	at io.sentry.OptionsContainer.createInstance(OptionsContainer.java:24)
	at io.sentry.Sentry.init(Sentry.java:115)
	at io.sentry.android.core.SentryAndroid.init(SentryAndroid.java:71)
	... 14 more
Caused by: java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:733)
	at com.zhihu.android.x.a.c.start(RulerThread.java:92)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:970)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1377)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:140)
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:633)
	at io.sentry.HostnameCache.updateCache(HostnameCache.java:97)
	at io.sentry.HostnameCache.<init>(HostnameCache.java:62)
	at io.sentry.HostnameCache.<init>(HostnameCache.java:49)
	at io.sentry.HostnameCache.<init>(HostnameCache.java:45)
	at io.sentry.MainEventProcessor.<init>(MainEventProcessor.java:32)
	at io.sentry.SentryOptions.<init>(SentryOptions.java:1516)
	at io.sentry.SentryOptions.<init>(SentryOptions.java:1496)
	at io.sentry.android.core.SentryAndroidOptions.<init>(SentryAndroidOptions.java:87)
	... 19 more

**Comment by EscapeA** [comment]
已知问题，webview 加载失败，跟 linker  有关

**Comment by tiann** [comment]
0.3.5 正常...

**Comment by tiann** [comment]
0.3.7 已修复，readlinktat 系统调用  `\0` 的问题。
