### ISSUE TITLE
AppOps 闪退

### ISSUE THREAD

**Issue by tiann** [twoyi/twoyi#74]
```txt
2022-02-25 12:12:46.799 14841-14841/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: rikka.appops, PID: 14841
    java.lang.UnsatisfiedLinkError: JNI_ERR returned from JNI_OnLoad in "/data/app/rikka.appops-DXpczTJ4D8gqjSDT_sGw0Q==/base.apk!/lib/arm64-v8a/libappops.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1657)
        at rikka.appops.app.AppOpsApplication.<init>(SourceFile:17)
        at java.lang.Class.newInstance(Native Method)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1102)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1087)
        at android.app.LoadedApk.makeApplication(LoadedApk.java:983)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5715)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1656)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

**Comment by canyie** [comment]
@RikkaW

**Comment by vvb2060** [comment]
预期行为，签名校验失败

**Comment by tiann** [comment]
vmos 或者其他虚拟机运行无问题，意味着他们可以破掉所谓的签名校验；是否说明这种签名验证方式有问题？

**Comment by vvb2060** [comment]
几个月前加了寄生式虚拟环境检测，一直没发版。关于签名检测，应该是因为打不开apk。

**Comment by tiann** [comment]
使用 openat 打开虚拟机内的 apk 路径，不过这个 openat 透过了虚拟机直接发到了 host，而虚拟机内的这个 apk 路径在宿主上是不存在的，所以会签名验证出错。

据我所知，vmos 也是通过 hook 的方式拦截了 openat；我在考虑要不要把这个也完善，但是考虑到后面会开源，很可能对别人会拿着这代码去破签名；最终又陷入无聊的猫鼠游戏之中...
