### ISSUE TITLE
Not installed 

### ISSUE THREAD

**Issue by Raif1** [twoyi/twoyi#89]
App not installed 

A sai error log for better understanding 

Shizuku installer error:

 Device: Phh Phh-Treble vanilla | Not MIUI | Android 11 | Using FilterApkSource ApkSource implementation | SAI 4.5

com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor$BadContentProviderException: DISPLAY_NAME column is null
	at com.aefyr.sai.model.filedescriptor.ContentUriFileDescriptor.name(ContentUriFileDescriptor.java:30)
	at com.aefyr.sai.model.apksource.DefaultApkSource.getApkName(DefaultApkSource.java:42)
	at com.aefyr.sai.model.apksource.SignerApkSource.getApkName(SignerApkSource.java:64)
	at com.aefyr.sai.model.apksource.SignerApkSource.nextApk(SignerApkSource.java:46)
	at com.aefyr.sai.model.apksource.FilterApkSource.nextApk(FilterApkSource.java:25)
	at com.aefyr.sai.installer2.impl.shell.ShellSaiPackageInstaller.install(ShellSaiPackageInstaller.java:112)
	at com.aefyr.sai.installer2.impl.shell.ShellSaiPackageInstaller.lambda$enqueueSession$0$ShellSaiPackageInstaller(ShellSaiPackageInstaller.java:93)
	at com.aefyr.sai.installer2.impl.shell.-$$Lambda$ShellSaiPackageInstaller$VdI3y9AkULdYCG2o9afJnUCfQnA.run(Unknown Source:6)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)

**Comment by xingshangyu** [comment]
您好，您的邮件已收到。祝好！

**Comment by Raif1** [comment]
Sir english

**Comment by tiann** [comment]
Please report the issue clearly.

**Comment by Raif1** [comment]
What do you mean ? How can i do ?

**Comment by starreeze123** [comment]
您好，您的邮件已收到。祝好！
